//go:build deps_only

// Code generated by protoc-gen-starpc-cpp. DO NOT EDIT.
// protoc-gen-starpc-cpp version: v0.45.1-0.20260203090429-3e915608d4e8
// source: github.com/aperturerobotics/starpc/mock/mock.proto

#include "mock_srpc.pb.hpp"

namespace e2e::mock {

starpc::Error SRPCMockClientImpl::MockRequest(const e2e::mock::MockMsg& in, e2e::mock::MockMsg* out) {
  return cc_->ExecCall(service_id_, "MockRequest", in, out);
}

std::vector<std::string> SRPCMockHandler::GetMethodIDs() const {
  return {
    "MockRequest",
  };
}

std::pair<bool, starpc::Error> SRPCMockHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "MockRequest") {
    e2e::mock::MockMsg req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    e2e::mock::MockMsg resp;
    err = impl_->MockRequest(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

}  // namespace e2e::mock
