version: "2"
run:
  concurrency: 4
  modules-download-mode: vendor
linters:
  enable:
    - depguard
    - gosec
    - importas
    - misspell
    - revive
    - unconvert
  disable:
    - errcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
            - pkg: github.com/stretchr/testify/assert
              desc: Use "gotest.tools/v3/assert" instead
            - pkg: github.com/stretchr/testify/require
              desc: Use "gotest.tools/v3/assert" instead
            - pkg: github.com/stretchr/testify/suite
              desc: Do not use
    gosec:
      excludes:
        - G306
    importas:
      no-unaliased: true
    revive:
      rules:
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - all
        - -SA1012
        - -ST1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
