// @generated
// This file is @generated by prost-build.
/// RpcStreamPacket is a packet encapsulating data for a RPC stream.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RpcStreamPacket {
    #[prost(oneof="rpc_stream_packet::Body", tags="1, 2, 3")]
    pub body: ::core::option::Option<rpc_stream_packet::Body>,
}
/// Nested message and enum types in `RpcStreamPacket`.
pub mod rpc_stream_packet {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        /// Init is the first packet in the stream.
        /// Sent by the initiator.
        #[prost(message, tag="1")]
        Init(super::RpcStreamInit),
        /// Ack is sent in response to Init.
        /// Sent by the server.
        #[prost(message, tag="2")]
        Ack(super::RpcAck),
        /// Data is the encapsulated data packet.
        #[prost(bytes, tag="3")]
        Data(::prost::alloc::vec::Vec<u8>),
    }
}
/// RpcStreamInit is the first message in a RPC stream.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RpcStreamInit {
    /// ComponentId is the identifier of the component making the request.
    #[prost(string, tag="1")]
    pub component_id: ::prost::alloc::string::String,
}
/// RpcAck is the ack message in a RPC stream.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RpcAck {
    /// Error indicates there was some error setting up the stream.
    #[prost(string, tag="1")]
    pub error: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
