// @generated by protoc-gen-es v1.8.0 with parameter "target=ts"
// @generated from file github.com/aperturerobotics/starpc/rpcstream/rpcstream.proto (package rpcstream, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from '@bufbuild/protobuf'
import { Message, proto3 } from '@bufbuild/protobuf'
import {
  RpcAck as RpcAck$1,
  RpcStreamInit as RpcStreamInit$1,
  RpcStreamPacket as RpcStreamPacket$1,
} from './rpcstream_pb.js'

/**
 * RpcStreamPacket is a packet encapsulating data for a RPC stream.
 *
 * @generated from message rpcstream.RpcStreamPacket
 */
export class RpcStreamPacket extends Message<RpcStreamPacket$1> {
  /**
   * @generated from oneof rpcstream.RpcStreamPacket.body
   */
  body:
    | {
        /**
         * Init is the first packet in the stream.
         * Sent by the initiator.
         *
         * @generated from field: rpcstream.RpcStreamInit init = 1;
         */
        value: RpcStreamInit$1
        case: 'init'
      }
    | {
        /**
         * Ack is sent in response to Init.
         * Sent by the server.
         *
         * @generated from field: rpcstream.RpcAck ack = 2;
         */
        value: RpcAck$1
        case: 'ack'
      }
    | {
        /**
         * Data is the encapsulated data packet.
         *
         * @generated from field: bytes data = 3;
         */
        value: Uint8Array
        case: 'data'
      }
    | { case: undefined; value?: undefined } = { case: undefined }

  constructor(data?: PartialMessage<RpcStreamPacket$1>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'rpcstream.RpcStreamPacket'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'init', kind: 'message', T: RpcStreamInit$1, oneof: 'body' },
    { no: 2, name: 'ack', kind: 'message', T: RpcAck$1, oneof: 'body' },
    {
      no: 3,
      name: 'data',
      kind: 'scalar',
      T: 12 /* ScalarType.BYTES */,
      oneof: 'body',
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RpcStreamPacket$1 {
    return new RpcStreamPacket$1().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RpcStreamPacket$1 {
    return new RpcStreamPacket$1().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RpcStreamPacket$1 {
    return new RpcStreamPacket$1().fromJsonString(jsonString, options)
  }

  static equals(
    a: RpcStreamPacket$1 | PlainMessage<RpcStreamPacket$1> | undefined,
    b: RpcStreamPacket$1 | PlainMessage<RpcStreamPacket$1> | undefined,
  ): boolean {
    return proto3.util.equals(RpcStreamPacket$1, a, b)
  }
}

/**
 * RpcStreamInit is the first message in a RPC stream.
 *
 * @generated from message rpcstream.RpcStreamInit
 */
export class RpcStreamInit extends Message<RpcStreamInit$1> {
  /**
   * ComponentId is the identifier of the component making the request.
   *
   * @generated from field: string component_id = 1;
   */
  componentId = ''

  constructor(data?: PartialMessage<RpcStreamInit$1>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'rpcstream.RpcStreamInit'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'component_id',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RpcStreamInit$1 {
    return new RpcStreamInit$1().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RpcStreamInit$1 {
    return new RpcStreamInit$1().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RpcStreamInit$1 {
    return new RpcStreamInit$1().fromJsonString(jsonString, options)
  }

  static equals(
    a: RpcStreamInit$1 | PlainMessage<RpcStreamInit$1> | undefined,
    b: RpcStreamInit$1 | PlainMessage<RpcStreamInit$1> | undefined,
  ): boolean {
    return proto3.util.equals(RpcStreamInit$1, a, b)
  }
}

/**
 * RpcAck is the ack message in a RPC stream.
 *
 * @generated from message rpcstream.RpcAck
 */
export class RpcAck extends Message<RpcAck$1> {
  /**
   * Error indicates there was some error setting up the stream.
   *
   * @generated from field: string error = 1;
   */
  error = ''

  constructor(data?: PartialMessage<RpcAck$1>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'rpcstream.RpcAck'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'error', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RpcAck$1 {
    return new RpcAck$1().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RpcAck$1 {
    return new RpcAck$1().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RpcAck$1 {
    return new RpcAck$1().fromJsonString(jsonString, options)
  }

  static equals(
    a: RpcAck$1 | PlainMessage<RpcAck$1> | undefined,
    b: RpcAck$1 | PlainMessage<RpcAck$1> | undefined,
  ): boolean {
    return proto3.util.equals(RpcAck$1, a, b)
  }
}
