//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/starpc/rpcstream/rpcstream.proto
// Protobuf C++ Version: 6.33.4

#include "rpcstream.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rpcstream {

inline constexpr RpcStreamInit::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        component_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RpcStreamInit::RpcStreamInit(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RpcStreamInit_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RpcStreamInitDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RpcStreamInitDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RpcStreamInitDefaultTypeInternal() {}
  union {
    RpcStreamInit _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RpcStreamInitDefaultTypeInternal _RpcStreamInit_default_instance_;

inline constexpr RpcAck::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        error_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RpcAck::RpcAck(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RpcAck_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RpcAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RpcAckDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RpcAckDefaultTypeInternal() {}
  union {
    RpcAck _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RpcAckDefaultTypeInternal _RpcAck_default_instance_;

inline constexpr RpcStreamPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : body_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR RpcStreamPacket::RpcStreamPacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RpcStreamPacket_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RpcStreamPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RpcStreamPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RpcStreamPacketDefaultTypeInternal() {}
  union {
    RpcStreamPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RpcStreamPacketDefaultTypeInternal _RpcStreamPacket_default_instance_;
}  // namespace rpcstream
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::rpcstream::RpcStreamPacket, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::rpcstream::RpcStreamPacket, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::rpcstream::RpcStreamPacket, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::rpcstream::RpcStreamPacket, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::rpcstream::RpcStreamPacket, _impl_.body_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rpcstream::RpcStreamInit, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rpcstream::RpcStreamInit, _impl_.component_id_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rpcstream::RpcAck, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rpcstream::RpcAck, _impl_.error_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::rpcstream::RpcStreamPacket)},
        {6, sizeof(::rpcstream::RpcStreamInit)},
        {11, sizeof(::rpcstream::RpcAck)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::rpcstream::_RpcStreamPacket_default_instance_._instance,
    &::rpcstream::_RpcStreamInit_default_instance_._instance,
    &::rpcstream::_RpcAck_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n<github.com/aperturerobotics/starpc/rpc"
    "stream/rpcstream.proto\022\trpcstream\"u\n\017Rpc"
    "StreamPacket\022(\n\004init\030\001 \001(\0132\030.rpcstream.R"
    "pcStreamInitH\000\022 \n\003ack\030\002 \001(\0132\021.rpcstream."
    "RpcAckH\000\022\016\n\004data\030\003 \001(\014H\000B\006\n\004body\"%\n\rRpcS"
    "treamInit\022\024\n\014component_id\030\001 \001(\t\"\027\n\006RpcAc"
    "k\022\r\n\005error\030\001 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto = {
    false,
    false,
    264,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto,
    "github.com/aperturerobotics/starpc/rpcstream/rpcstream.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto,
};
namespace rpcstream {
// ===================================================================

class RpcStreamPacket::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::rpcstream::RpcStreamPacket, _impl_._oneof_case_);
};

void RpcStreamPacket::set_allocated_init(::rpcstream::RpcStreamInit* PROTOBUF_NULLABLE init) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (init) {
    ::google::protobuf::Arena* submessage_arena = init->GetArena();
    if (message_arena != submessage_arena) {
      init = ::google::protobuf::internal::GetOwnedMessage(message_arena, init, submessage_arena);
    }
    set_has_init();
    _impl_.body_.init_ = init;
  }
  // @@protoc_insertion_point(field_set_allocated:rpcstream.RpcStreamPacket.init)
}
void RpcStreamPacket::set_allocated_ack(::rpcstream::RpcAck* PROTOBUF_NULLABLE ack) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (ack) {
    ::google::protobuf::Arena* submessage_arena = ack->GetArena();
    if (message_arena != submessage_arena) {
      ack = ::google::protobuf::internal::GetOwnedMessage(message_arena, ack, submessage_arena);
    }
    set_has_ack();
    _impl_.body_.ack_ = ack;
  }
  // @@protoc_insertion_point(field_set_allocated:rpcstream.RpcStreamPacket.ack)
}
RpcStreamPacket::RpcStreamPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcStreamPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpcstream.RpcStreamPacket)
}
PROTOBUF_NDEBUG_INLINE RpcStreamPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rpcstream::RpcStreamPacket& from_msg)
      : body_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

RpcStreamPacket::RpcStreamPacket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RpcStreamPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcStreamPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RpcStreamPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (body_case()) {
    case BODY_NOT_SET:
      break;
      case kInit:
        _impl_.body_.init_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.init_);
        break;
      case kAck:
        _impl_.body_.ack_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.ack_);
        break;
      case kData:
        new (&_impl_.body_.data_) decltype(_impl_.body_.data_){arena, from._impl_.body_.data_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:rpcstream.RpcStreamPacket)
}
PROTOBUF_NDEBUG_INLINE RpcStreamPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : body_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void RpcStreamPacket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RpcStreamPacket::~RpcStreamPacket() {
  // @@protoc_insertion_point(destructor:rpcstream.RpcStreamPacket)
  SharedDtor(*this);
}
inline void RpcStreamPacket::SharedDtor(MessageLite& self) {
  RpcStreamPacket& this_ = static_cast<RpcStreamPacket&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_body()) {
    this_.clear_body();
  }
  this_._impl_.~Impl_();
}

void RpcStreamPacket::clear_body() {
// @@protoc_insertion_point(one_of_clear_start:rpcstream.RpcStreamPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (body_case()) {
    case kInit: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.init_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.init_);
      }
      break;
    }
    case kAck: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.ack_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.ack_);
      }
      break;
    }
    case kData: {
      _impl_.body_.data_.Destroy();
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}


inline void* PROTOBUF_NONNULL RpcStreamPacket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RpcStreamPacket(arena);
}
constexpr auto RpcStreamPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RpcStreamPacket),
                                            alignof(RpcStreamPacket));
}
constexpr auto RpcStreamPacket::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RpcStreamPacket_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RpcStreamPacket::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RpcStreamPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RpcStreamPacket::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RpcStreamPacket>(), &RpcStreamPacket::ByteSizeLong,
              &RpcStreamPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RpcStreamPacket, _impl_._cached_size_),
          false,
      },
      &RpcStreamPacket::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RpcStreamPacket_class_data_ =
        RpcStreamPacket::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RpcStreamPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RpcStreamPacket_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RpcStreamPacket_class_data_.tc_table);
  return RpcStreamPacket_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 2, 0, 2>
RpcStreamPacket::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    RpcStreamPacket_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rpcstream::RpcStreamPacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .rpcstream.RpcStreamInit init = 1;
    {PROTOBUF_FIELD_OFFSET(RpcStreamPacket, _impl_.body_.init_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rpcstream.RpcAck ack = 2;
    {PROTOBUF_FIELD_OFFSET(RpcStreamPacket, _impl_.body_.ack_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes data = 3;
    {PROTOBUF_FIELD_OFFSET(RpcStreamPacket, _impl_.body_.data_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::rpcstream::RpcStreamInit>()},
      {::_pbi::TcParser::GetTable<::rpcstream::RpcAck>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void RpcStreamPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:rpcstream.RpcStreamPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_body();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RpcStreamPacket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RpcStreamPacket& this_ = static_cast<const RpcStreamPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RpcStreamPacket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RpcStreamPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rpcstream.RpcStreamPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.body_case()) {
    case kInit: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.body_.init_, this_._impl_.body_.init_->GetCachedSize(), target,
          stream);
      break;
    }
    case kAck: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.body_.ack_, this_._impl_.body_.ack_->GetCachedSize(), target,
          stream);
      break;
    }
    case kData: {
      const ::std::string& _s = this_._internal_data();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpcstream.RpcStreamPacket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RpcStreamPacket::ByteSizeLong(const MessageLite& base) {
  const RpcStreamPacket& this_ = static_cast<const RpcStreamPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RpcStreamPacket::ByteSizeLong() const {
  const RpcStreamPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rpcstream.RpcStreamPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.body_case()) {
    // .rpcstream.RpcStreamInit init = 1;
    case kInit: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.init_);
      break;
    }
    // .rpcstream.RpcAck ack = 2;
    case kAck: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.ack_);
      break;
    }
    // bytes data = 3;
    case kData: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_data());
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RpcStreamPacket::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RpcStreamPacket*>(&to_msg);
  auto& from = static_cast<const RpcStreamPacket&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rpcstream.RpcStreamPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_body();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kInit: {
        if (oneof_needs_init) {
          _this->_impl_.body_.init_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.init_);
        } else {
          _this->_impl_.body_.init_->MergeFrom(*from._impl_.body_.init_);
        }
        break;
      }
      case kAck: {
        if (oneof_needs_init) {
          _this->_impl_.body_.ack_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.ack_);
        } else {
          _this->_impl_.body_.ack_->MergeFrom(*from._impl_.body_.ack_);
        }
        break;
      }
      case kData: {
        if (oneof_needs_init) {
          _this->_impl_.body_.data_.InitDefault();
        }
        _this->_impl_.body_.data_.Set(from._internal_data(), arena);
        break;
      }
      case BODY_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RpcStreamPacket::CopyFrom(const RpcStreamPacket& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:rpcstream.RpcStreamPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RpcStreamPacket::InternalSwap(RpcStreamPacket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.body_, other->_impl_.body_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata RpcStreamPacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RpcStreamInit::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RpcStreamInit>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RpcStreamInit, _impl_._has_bits_);
};

RpcStreamInit::RpcStreamInit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcStreamInit_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpcstream.RpcStreamInit)
}
PROTOBUF_NDEBUG_INLINE RpcStreamInit::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rpcstream::RpcStreamInit& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        component_id_(arena, from.component_id_) {}

RpcStreamInit::RpcStreamInit(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RpcStreamInit& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcStreamInit_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RpcStreamInit* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rpcstream.RpcStreamInit)
}
PROTOBUF_NDEBUG_INLINE RpcStreamInit::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        component_id_(arena) {}

inline void RpcStreamInit::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RpcStreamInit::~RpcStreamInit() {
  // @@protoc_insertion_point(destructor:rpcstream.RpcStreamInit)
  SharedDtor(*this);
}
inline void RpcStreamInit::SharedDtor(MessageLite& self) {
  RpcStreamInit& this_ = static_cast<RpcStreamInit&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.component_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RpcStreamInit::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RpcStreamInit(arena);
}
constexpr auto RpcStreamInit::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RpcStreamInit),
                                            alignof(RpcStreamInit));
}
constexpr auto RpcStreamInit::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RpcStreamInit_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RpcStreamInit::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RpcStreamInit>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RpcStreamInit::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RpcStreamInit>(), &RpcStreamInit::ByteSizeLong,
              &RpcStreamInit::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RpcStreamInit, _impl_._cached_size_),
          false,
      },
      &RpcStreamInit::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RpcStreamInit_class_data_ =
        RpcStreamInit::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RpcStreamInit::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RpcStreamInit_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RpcStreamInit_class_data_.tc_table);
  return RpcStreamInit_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 44, 2>
RpcStreamInit::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RpcStreamInit, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RpcStreamInit_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rpcstream::RpcStreamInit>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string component_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RpcStreamInit, _impl_.component_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string component_id = 1;
    {PROTOBUF_FIELD_OFFSET(RpcStreamInit, _impl_.component_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\14\0\0\0\0\0\0"
    "rpcstream.RpcStreamInit"
    "component_id"
  }},
};
PROTOBUF_NOINLINE void RpcStreamInit::Clear() {
// @@protoc_insertion_point(message_clear_start:rpcstream.RpcStreamInit)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.component_id_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RpcStreamInit::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RpcStreamInit& this_ = static_cast<const RpcStreamInit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RpcStreamInit::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RpcStreamInit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rpcstream.RpcStreamInit)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string component_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_component_id().empty()) {
      const ::std::string& _s = this_._internal_component_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpcstream.RpcStreamInit.component_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpcstream.RpcStreamInit)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RpcStreamInit::ByteSizeLong(const MessageLite& base) {
  const RpcStreamInit& this_ = static_cast<const RpcStreamInit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RpcStreamInit::ByteSizeLong() const {
  const RpcStreamInit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rpcstream.RpcStreamInit)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string component_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_component_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_component_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RpcStreamInit::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RpcStreamInit*>(&to_msg);
  auto& from = static_cast<const RpcStreamInit&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:rpcstream.RpcStreamInit)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_component_id().empty()) {
      _this->_internal_set_component_id(from._internal_component_id());
    } else {
      if (_this->_impl_.component_id_.IsDefault()) {
        _this->_internal_set_component_id("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RpcStreamInit::CopyFrom(const RpcStreamInit& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:rpcstream.RpcStreamInit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RpcStreamInit::InternalSwap(RpcStreamInit* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.component_id_, &other->_impl_.component_id_, arena);
}

::google::protobuf::Metadata RpcStreamInit::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RpcAck::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RpcAck>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RpcAck, _impl_._has_bits_);
};

RpcAck::RpcAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcAck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpcstream.RpcAck)
}
PROTOBUF_NDEBUG_INLINE RpcAck::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rpcstream::RpcAck& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        error_(arena, from.error_) {}

RpcAck::RpcAck(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RpcAck& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcAck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RpcAck* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rpcstream.RpcAck)
}
PROTOBUF_NDEBUG_INLINE RpcAck::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        error_(arena) {}

inline void RpcAck::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RpcAck::~RpcAck() {
  // @@protoc_insertion_point(destructor:rpcstream.RpcAck)
  SharedDtor(*this);
}
inline void RpcAck::SharedDtor(MessageLite& self) {
  RpcAck& this_ = static_cast<RpcAck&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.error_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RpcAck::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RpcAck(arena);
}
constexpr auto RpcAck::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RpcAck),
                                            alignof(RpcAck));
}
constexpr auto RpcAck::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RpcAck_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RpcAck::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RpcAck>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RpcAck::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RpcAck>(), &RpcAck::ByteSizeLong,
              &RpcAck::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RpcAck, _impl_._cached_size_),
          false,
      },
      &RpcAck::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RpcAck_class_data_ =
        RpcAck::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RpcAck::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RpcAck_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RpcAck_class_data_.tc_table);
  return RpcAck_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2>
RpcAck::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RpcAck, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RpcAck_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rpcstream::RpcAck>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RpcAck, _impl_.error_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string error = 1;
    {PROTOBUF_FIELD_OFFSET(RpcAck, _impl_.error_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\5\0\0\0\0\0\0"
    "rpcstream.RpcAck"
    "error"
  }},
};
PROTOBUF_NOINLINE void RpcAck::Clear() {
// @@protoc_insertion_point(message_clear_start:rpcstream.RpcAck)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.error_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RpcAck::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RpcAck& this_ = static_cast<const RpcAck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RpcAck::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RpcAck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rpcstream.RpcAck)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string error = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_error().empty()) {
      const ::std::string& _s = this_._internal_error();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpcstream.RpcAck.error");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpcstream.RpcAck)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RpcAck::ByteSizeLong(const MessageLite& base) {
  const RpcAck& this_ = static_cast<const RpcAck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RpcAck::ByteSizeLong() const {
  const RpcAck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rpcstream.RpcAck)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string error = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_error().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_error());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RpcAck::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RpcAck*>(&to_msg);
  auto& from = static_cast<const RpcAck&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:rpcstream.RpcAck)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_error().empty()) {
      _this->_internal_set_error(from._internal_error());
    } else {
      if (_this->_impl_.error_.IsDefault()) {
        _this->_internal_set_error("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RpcAck::CopyFrom(const RpcAck& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:rpcstream.RpcAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RpcAck::InternalSwap(RpcAck* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_, &other->_impl_.error_, arena);
}

::google::protobuf::Metadata RpcAck::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rpcstream
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
