[project]
name = "starpc-python-plugin"
version = "0.52.0"
requires-python = ">=3.14,<3.15"
dependencies = ["protobuf==7.36.1", "ruff==0.16.6"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

[project.scripts]
protoc-gen-starpc-python = "starpc_plugin:main"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"
