[project]
name = "starpc-python-plugin"
version = "0.52.0"
requires-python = ">=3.14,<3.15"
dependencies = ["protobuf==7.35.1", "ruff==0.16.2"]

[project.scripts]
protoc-gen-starpc-python = "starpc_plugin:main"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"
