import { MethodIdempotency, MethodKind } from '@bufbuild/protobuf'
import { MessageType } from '@aptre/protobuf-es-lite'

// ServiceMethodDefinitions is the type of the methods map on the service definition.
export type ServiceMethodDefinitions = {
  [id: string]: MethodDefinition<
    MessageType,
    MessageType,
    MethodKind,
    MethodIdempotency | undefined
  >
}

// ServiceDefinition describes the service definitions generated by protoc-gen-es-starpc.
export interface ServiceDefinition<
  MethodDefinitions extends ServiceMethodDefinitions,
> {
  // typeName is the fully qualified name of the service
  // Example: echo.Echoer
  typeName: string
  // methods is the set of available RPC methods.
  methods: MethodDefinitions
}

// MethodDefinition describes the service method definitions generated by protoc-gen-es-starpc.
export interface MethodDefinition<
  RequestT extends MessageType,
  ResponseT extends MessageType,
  MethodK extends MethodKind,
  MethodI extends MethodIdempotency | undefined,
> {
  // name is the name and function name of the method.
  // e.x.: Echo
  name: string
  // I is the message type used for the request.
  I: RequestT
  // O is the message type used for the response.
  O: ResponseT
  // kind is the rpc kind.
  kind: MethodK
  // idempotency is the idempotency of the method.
  idempotency?: MethodI
}
