// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.16.0
// source: github.com/aperturerobotics/starpc/srpc/rpcproto.proto

package srpc

import (
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
)

// ErrorCode classifies failures that callers must distinguish from handler errors.
type ErrorCode int32

const (
	// ERROR_CODE_UNKNOWN leaves Error as an ordinary handler diagnostic.
	ErrorCode_ERROR_CODE_UNKNOWN ErrorCode = 0
	// ERROR_CODE_RESET reports that the forwarded transport was reset.
	ErrorCode_ERROR_CODE_RESET ErrorCode = 1
	// ERROR_CODE_CLOSED_BEFORE_COMPLETION reports a transport closed without a verdict.
	ErrorCode_ERROR_CODE_CLOSED_BEFORE_COMPLETION ErrorCode = 2
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNKNOWN",
		1: "ERROR_CODE_RESET",
		2: "ERROR_CODE_CLOSED_BEFORE_COMPLETION",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNKNOWN":                  0,
		"ERROR_CODE_RESET":                    1,
		"ERROR_CODE_CLOSED_BEFORE_COMPLETION": 2,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	name, valid := ErrorCode_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// Packet is a message sent over a srpc packet connection.
type Packet struct {
	unknownFields []byte
	// Body is the packet body.
	//
	// Types that are assignable to Body:
	//	*Packet_CallStart
	//	*Packet_CallData
	//	*Packet_CallCancel
	Body isPacket_Body `protobuf_oneof:"body"`
}

func (x *Packet) Reset() {
	*x = Packet{}
}

func (*Packet) ProtoMessage() {}

func (m *Packet) GetBody() isPacket_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Packet) GetCallStart() *CallStart {
	if x, ok := x.GetBody().(*Packet_CallStart); ok {
		return x.CallStart
	}
	return nil
}

func (x *Packet) GetCallData() *CallData {
	if x, ok := x.GetBody().(*Packet_CallData); ok {
		return x.CallData
	}
	return nil
}

func (x *Packet) GetCallCancel() bool {
	if x, ok := x.GetBody().(*Packet_CallCancel); ok {
		return x.CallCancel
	}
	return false
}

type isPacket_Body interface {
	isPacket_Body()
}

type Packet_CallStart struct {
	// CallStart initiates a new call.
	CallStart *CallStart `protobuf:"bytes,1,opt,name=call_start,json=callStart,proto3,oneof"`
}

type Packet_CallData struct {
	// CallData is a message in a streaming RPC sequence.
	CallData *CallData `protobuf:"bytes,2,opt,name=call_data,json=callData,proto3,oneof"`
}

type Packet_CallCancel struct {
	// CallCancel cancels the call.
	CallCancel bool `protobuf:"varint,3,opt,name=call_cancel,json=callCancel,proto3,oneof"`
}

func (*Packet_CallStart) isPacket_Body() {}

func (*Packet_CallData) isPacket_Body() {}

func (*Packet_CallCancel) isPacket_Body() {}

// CallStart requests starting a new RPC call.
type CallStart struct {
	unknownFields []byte
	// RpcService is the service to contact.
	// Must be set.
	RpcService string `protobuf:"bytes,1,opt,name=rpc_service,json=rpcService,proto3" json:"rpcService,omitempty"`
	// RpcMethod is the RPC method to call.
	// Must be set.
	RpcMethod string `protobuf:"bytes,2,opt,name=rpc_method,json=rpcMethod,proto3" json:"rpcMethod,omitempty"`
	// Data contains the request or the first message in the stream.
	// Optional if streaming.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// DataIsZero indicates Data is set with an empty message.
	DataIsZero bool `protobuf:"varint,4,opt,name=data_is_zero,json=dataIsZero,proto3" json:"dataIsZero,omitempty"`
}

func (x *CallStart) Reset() {
	*x = CallStart{}
}

func (*CallStart) ProtoMessage() {}

func (x *CallStart) GetRpcService() string {
	if x != nil {
		return x.RpcService
	}
	return ""
}

func (x *CallStart) GetRpcMethod() string {
	if x != nil {
		return x.RpcMethod
	}
	return ""
}

func (x *CallStart) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CallStart) GetDataIsZero() bool {
	if x != nil {
		return x.DataIsZero
	}
	return false
}

// CallData contains a message in a streaming RPC sequence.
type CallData struct {
	unknownFields []byte
	// Data contains the packet in the sequence.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// DataIsZero indicates Data is set with an empty message.
	DataIsZero bool `protobuf:"varint,2,opt,name=data_is_zero,json=dataIsZero,proto3" json:"dataIsZero,omitempty"`
	// Complete indicates the RPC call is completed.
	Complete bool `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	// Error contains any error that caused the RPC to fail.
	// If set, implies complete=true.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// ErrorCode preserves transport failures through RPC forwarding.
	// A nonzero code implies complete=true; Error retains the diagnostic text.
	ErrorCode ErrorCode `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3" json:"errorCode,omitempty"`
}

func (x *CallData) Reset() {
	*x = CallData{}
}

func (*CallData) ProtoMessage() {}

func (x *CallData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CallData) GetDataIsZero() bool {
	if x != nil {
		return x.DataIsZero
	}
	return false
}

func (x *CallData) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *CallData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CallData) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNKNOWN
}

func (m *Packet) CloneVT() *Packet {
	if m == nil {
		return (*Packet)(nil)
	}
	r := new(Packet)
	if m.Body != nil {
		r.Body = m.Body.(interface{ CloneOneofVT() isPacket_Body }).CloneOneofVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Packet) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Packet_CallStart) CloneVT() *Packet_CallStart {
	if m == nil {
		return (*Packet_CallStart)(nil)
	}
	r := new(Packet_CallStart)
	r.CallStart = protobuf_go_lite.CloneVTValue(m.CallStart)
	return r
}

func (m *Packet_CallStart) CloneOneofVT() isPacket_Body {
	return m.CloneVT()
}

func (m *Packet_CallData) CloneVT() *Packet_CallData {
	if m == nil {
		return (*Packet_CallData)(nil)
	}
	r := new(Packet_CallData)
	r.CallData = protobuf_go_lite.CloneVTValue(m.CallData)
	return r
}

func (m *Packet_CallData) CloneOneofVT() isPacket_Body {
	return m.CloneVT()
}

func (m *Packet_CallCancel) CloneVT() *Packet_CallCancel {
	if m == nil {
		return (*Packet_CallCancel)(nil)
	}
	r := new(Packet_CallCancel)
	r.CallCancel = m.CallCancel
	return r
}

func (m *Packet_CallCancel) CloneOneofVT() isPacket_Body {
	return m.CloneVT()
}

func (m *CallStart) CloneVT() *CallStart {
	if m == nil {
		return (*CallStart)(nil)
	}
	r := new(CallStart)
	r.RpcService = m.RpcService
	r.RpcMethod = m.RpcMethod
	r.DataIsZero = m.DataIsZero
	r.Data = protobuf_go_lite.CloneBytes(m.Data)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CallStart) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CallData) CloneVT() *CallData {
	if m == nil {
		return (*CallData)(nil)
	}
	r := new(CallData)
	r.DataIsZero = m.DataIsZero
	r.Complete = m.Complete
	r.Error = m.Error
	r.ErrorCode = m.ErrorCode
	r.Data = protobuf_go_lite.CloneBytes(m.Data)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CallData) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *Packet) EqualVT(that *Packet) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Body == nil && that.Body != nil {
		return false
	} else if this.Body != nil {
		if that.Body == nil {
			return false
		}
		if !this.Body.(interface{ EqualVT(isPacket_Body) bool }).EqualVT(that.Body) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Packet) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Packet)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Packet_CallStart) EqualVT(thatIface isPacket_Body) bool {
	that, ok := thatIface.(*Packet_CallStart)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.CallStart, that.CallStart, func() *CallStart { return &CallStart{} }) {
		return false
	}
	return true
}

func (this *Packet_CallData) EqualVT(thatIface isPacket_Body) bool {
	that, ok := thatIface.(*Packet_CallData)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.CallData, that.CallData, func() *CallData { return &CallData{} }) {
		return false
	}
	return true
}

func (this *Packet_CallCancel) EqualVT(thatIface isPacket_Body) bool {
	that, ok := thatIface.(*Packet_CallCancel)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.CallCancel != that.CallCancel {
		return false
	}
	return true
}

func (this *CallStart) EqualVT(that *CallStart) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.RpcService != that.RpcService {
		return false
	}
	if this.RpcMethod != that.RpcMethod {
		return false
	}
	if !protobuf_go_lite.EqualBytes(this.Data, that.Data) {
		return false
	}
	if this.DataIsZero != that.DataIsZero {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CallStart) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CallStart)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CallData) EqualVT(that *CallData) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualBytes(this.Data, that.Data) {
		return false
	}
	if this.DataIsZero != that.DataIsZero {
		return false
	}
	if this.Complete != that.Complete {
		return false
	}
	if this.Error != that.Error {
		return false
	}
	if this.ErrorCode != that.ErrorCode {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CallData) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CallData)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the ErrorCode to JSON.
func (x ErrorCode) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), ErrorCode_name)
}

// MarshalText marshals the ErrorCode to text.
func (x ErrorCode) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), ErrorCode_name)), nil
}

// MarshalJSON marshals the ErrorCode to JSON.
func (x ErrorCode) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ErrorCode from JSON.
func (x *ErrorCode) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(ErrorCode_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read ErrorCode enum: %v", err)
		return
	}
	*x = ErrorCode(v)
}

// UnmarshalText unmarshals the ErrorCode from text.
func (x *ErrorCode) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), ErrorCode_value)
	if err != nil {
		return err
	}
	*x = ErrorCode(i)
	return nil
}

// UnmarshalJSON unmarshals the ErrorCode from JSON.
func (x *ErrorCode) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Packet message to JSON.
func (x *Packet) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Body != nil {
		switch ov := x.Body.(type) {
		case *Packet_CallStart:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("callStart")
			ov.CallStart.MarshalProtoJSON(s.WithField("callStart"))
		case *Packet_CallData:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("callData")
			ov.CallData.MarshalProtoJSON(s.WithField("callData"))
		case *Packet_CallCancel:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("callCancel")
			s.WriteBool(ov.CallCancel)
		}
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Packet to JSON.
func (x *Packet) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Packet message from JSON.
func (x *Packet) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "call_start", "callStart":
			ov := &Packet_CallStart{}
			x.Body = ov
			if s.ReadNil() {
				ov.CallStart = nil
				return
			}
			ov.CallStart = &CallStart{}
			ov.CallStart.UnmarshalProtoJSON(s.WithField("call_start", true))
		case "call_data", "callData":
			ov := &Packet_CallData{}
			x.Body = ov
			if s.ReadNil() {
				ov.CallData = nil
				return
			}
			ov.CallData = &CallData{}
			ov.CallData.UnmarshalProtoJSON(s.WithField("call_data", true))
		case "call_cancel", "callCancel":
			s.AddField("call_cancel")
			ov := &Packet_CallCancel{}
			x.Body = ov
			ov.CallCancel = s.ReadBool()
		}
	})
}

// UnmarshalJSON unmarshals the Packet from JSON.
func (x *Packet) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the CallStart message to JSON.
func (x *CallStart) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.RpcService != "" || s.HasField("rpcService") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("rpcService")
		s.WriteString(x.RpcService)
	}
	if x.RpcMethod != "" || s.HasField("rpcMethod") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("rpcMethod")
		s.WriteString(x.RpcMethod)
	}
	if len(x.Data) > 0 || s.HasField("data") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("data")
		s.WriteBytes(x.Data)
	}
	if x.DataIsZero || s.HasField("dataIsZero") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("dataIsZero")
		s.WriteBool(x.DataIsZero)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the CallStart to JSON.
func (x *CallStart) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the CallStart message from JSON.
func (x *CallStart) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "rpc_service", "rpcService":
			s.AddField("rpc_service")
			x.RpcService = s.ReadString()
		case "rpc_method", "rpcMethod":
			s.AddField("rpc_method")
			x.RpcMethod = s.ReadString()
		case "data":
			s.AddField("data")
			x.Data = s.ReadBytes()
		case "data_is_zero", "dataIsZero":
			s.AddField("data_is_zero")
			x.DataIsZero = s.ReadBool()
		}
	})
}

// UnmarshalJSON unmarshals the CallStart from JSON.
func (x *CallStart) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the CallData message to JSON.
func (x *CallData) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Data) > 0 || s.HasField("data") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("data")
		s.WriteBytes(x.Data)
	}
	if x.DataIsZero || s.HasField("dataIsZero") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("dataIsZero")
		s.WriteBool(x.DataIsZero)
	}
	if x.Complete || s.HasField("complete") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("complete")
		s.WriteBool(x.Complete)
	}
	if x.Error != "" || s.HasField("error") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("error")
		s.WriteString(x.Error)
	}
	if x.ErrorCode != 0 || s.HasField("errorCode") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("errorCode")
		x.ErrorCode.MarshalProtoJSON(s)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the CallData to JSON.
func (x *CallData) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the CallData message from JSON.
func (x *CallData) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "data":
			s.AddField("data")
			x.Data = s.ReadBytes()
		case "data_is_zero", "dataIsZero":
			s.AddField("data_is_zero")
			x.DataIsZero = s.ReadBool()
		case "complete":
			s.AddField("complete")
			x.Complete = s.ReadBool()
		case "error":
			s.AddField("error")
			x.Error = s.ReadString()
		case "error_code", "errorCode":
			s.AddField("error_code")
			x.ErrorCode.UnmarshalProtoJSON(s)
		}
	})
}

// UnmarshalJSON unmarshals the CallData from JSON.
func (x *CallData) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *Packet) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Packet) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Packet) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if vtmsg, ok := m.Body.(interface {
		MarshalToSizedBufferVT([]byte) (int, error)
	}); ok {
		size, err := vtmsg.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
	}
	return len(dAtA) - i, nil
}

func (m *Packet_CallStart) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Packet_CallStart) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CallStart != nil {
		size, err := m.CallStart.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Packet_CallData) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Packet_CallData) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CallData != nil {
		size, err := m.CallData.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *Packet_CallCancel) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Packet_CallCancel) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = protobuf_go_lite.EncodeBool(dAtA, i, m.CallCancel)
	i--
	dAtA[i] = 0x18
	return len(dAtA) - i, nil
}

func (m *CallStart) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallStart) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CallStart) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.DataIsZero {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.DataIsZero)
		i--
		dAtA[i] = 0x20
	}
	if len(m.Data) > 0 {
		i = protobuf_go_lite.EncodeBytes(dAtA, i, m.Data)
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RpcMethod) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.RpcMethod)
		i--
		dAtA[i] = 0x12
	}
	if len(m.RpcService) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.RpcService)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CallData) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallData) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CallData) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.ErrorCode != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.ErrorCode))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Error) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Error)
		i--
		dAtA[i] = 0x22
	}
	if m.Complete {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.Complete)
		i--
		dAtA[i] = 0x18
	}
	if m.DataIsZero {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.DataIsZero)
		i--
		dAtA[i] = 0x10
	}
	if len(m.Data) > 0 {
		i = protobuf_go_lite.EncodeBytes(dAtA, i, m.Data)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Packet) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if vtmsg, ok := m.Body.(interface{ SizeVT() int }); ok {
		n += vtmsg.SizeVT()
	}
	n += len(m.unknownFields)
	return n
}

func (m *Packet_CallStart) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CallStart != nil {
		l = m.CallStart.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Packet_CallData) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CallData != nil {
		l = m.CallData.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Packet_CallCancel) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBoolValue(1)
	return n
}

func (m *CallStart) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.RpcService)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.RpcMethod)
	n += protobuf_go_lite.SizeBytesNonEmpty(1, m.Data)
	n += protobuf_go_lite.SizeBoolNonZero(1, m.DataIsZero)
	n += len(m.unknownFields)
	return n
}

func (m *CallData) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBytesNonEmpty(1, m.Data)
	n += protobuf_go_lite.SizeBoolNonZero(1, m.DataIsZero)
	n += protobuf_go_lite.SizeBoolNonZero(1, m.Complete)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Error)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.ErrorCode)
	n += len(m.unknownFields)
	return n
}

func (x ErrorCode) MarshalProtoText() string {
	return x.String()
}

func (x *Packet) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Packet")
	switch body := x.Body.(type) {
	case *Packet_CallStart:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "call_start")
		if body.CallStart == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &CallStart{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.CallStart)
		}
	case *Packet_CallData:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "call_data")
		if body.CallData == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &CallData{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.CallData)
		}
	case *Packet_CallCancel:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "call_cancel")
		protobuf_go_lite.TextWriteBool(&sb, body.CallCancel)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Packet) String() string {
	return x.MarshalProtoText()
}

func (x *CallStart) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CallStart")
	if x.RpcService != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "rpc_service")
		protobuf_go_lite.TextWriteString(&sb, x.RpcService)
	}
	if x.RpcMethod != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "rpc_method")
		protobuf_go_lite.TextWriteString(&sb, x.RpcMethod)
	}
	if len(x.Data) != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "data")
		protobuf_go_lite.TextWriteBytes(&sb, x.Data)
	}
	if x.DataIsZero != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "data_is_zero")
		protobuf_go_lite.TextWriteBool(&sb, x.DataIsZero)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CallStart) String() string {
	return x.MarshalProtoText()
}

func (x *CallData) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CallData")
	if len(x.Data) != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "data")
		protobuf_go_lite.TextWriteBytes(&sb, x.Data)
	}
	if x.DataIsZero != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "data_is_zero")
		protobuf_go_lite.TextWriteBool(&sb, x.DataIsZero)
	}
	if x.Complete != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "complete")
		protobuf_go_lite.TextWriteBool(&sb, x.Complete)
	}
	if x.Error != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "error")
		protobuf_go_lite.TextWriteString(&sb, x.Error)
	}
	if x.ErrorCode != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "error_code")
		protobuf_go_lite.TextWriteStringer(&sb, ErrorCode(x.ErrorCode))
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CallData) String() string {
	return x.MarshalProtoText()
}

func (m *Packet) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Packet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Packet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallStart", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Packet_CallStart); ok {
				if err := oneof.CallStart.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &CallStart{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Packet_CallStart{CallStart: v}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallData", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Packet_CallData); ok {
				if err := oneof.CallData.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &CallData{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Packet_CallData{CallData: v}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallCancel", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.Body = &Packet_CallCancel{CallCancel: b}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CallStart) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallStart: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallStart: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpcService", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.RpcService = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpcMethod", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.RpcMethod = v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			m.Data, iNdEx, err = protobuf_go_lite.DecodeBytesAppend(m.Data, dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataIsZero", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DataIsZero = bool(v)
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CallData) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			m.Data, iNdEx, err = protobuf_go_lite.DecodeBytesAppend(m.Data, dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataIsZero", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DataIsZero = bool(v)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Complete", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Complete = bool(v)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Error = v
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			m.ErrorCode = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.ErrorCode = ErrorCode(_v)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
