// @generated
// This file is @generated by prost-build.
/// Packet is a message sent over a srpc packet connection.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Packet {
    /// Body is the packet body.
    #[prost(oneof="packet::Body", tags="1, 2, 3")]
    pub body: ::core::option::Option<packet::Body>,
}
/// Nested message and enum types in `Packet`.
pub mod packet {
    /// Body is the packet body.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        /// CallStart initiates a new call.
        #[prost(message, tag="1")]
        CallStart(super::CallStart),
        /// CallData is a message in a streaming RPC sequence.
        #[prost(message, tag="2")]
        CallData(super::CallData),
        /// CallCancel cancels the call.
        #[prost(bool, tag="3")]
        CallCancel(bool),
    }
}
/// CallStart requests starting a new RPC call.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CallStart {
    /// RpcService is the service to contact.
    /// Must be set.
    #[prost(string, tag="1")]
    pub rpc_service: ::prost::alloc::string::String,
    /// RpcMethod is the RPC method to call.
    /// Must be set.
    #[prost(string, tag="2")]
    pub rpc_method: ::prost::alloc::string::String,
    /// Data contains the request or the first message in the stream.
    /// Optional if streaming.
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// DataIsZero indicates Data is set with an empty message.
    #[prost(bool, tag="4")]
    pub data_is_zero: bool,
}
/// CallData contains a message in a streaming RPC sequence.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CallData {
    /// Data contains the packet in the sequence.
    #[prost(bytes="vec", tag="1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// DataIsZero indicates Data is set with an empty message.
    #[prost(bool, tag="2")]
    pub data_is_zero: bool,
    /// Complete indicates the RPC call is completed.
    #[prost(bool, tag="3")]
    pub complete: bool,
    /// Error contains any error that caused the RPC to fail.
    /// If set, implies complete=true.
    #[prost(string, tag="4")]
    pub error: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
