// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/starpc/srpc/rpcproto.proto (package srpc, syntax proto3)
/* eslint-disable */

import { createEnumType } from '@aptre/protobuf-es-lite/enum'
import type { MessageType } from '@aptre/protobuf-es-lite/message'
import { createMessageType } from '@aptre/protobuf-es-lite/message'
import { ScalarType } from '@aptre/protobuf-es-lite/scalar'
import type { PartialFieldInfo } from '@aptre/protobuf-es-lite/field'

export const protobufPackage = 'srpc'

/**
 * TerminalKind is the terminal state of a held unary invocation.
 *
 * @generated from enum srpc.TerminalKind
 */
export enum TerminalKind {
  /**
   * TERMINAL_KIND_UNSPECIFIED is not a valid terminal state.
   *
   * @generated from enum value: TERMINAL_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * TERMINAL_KIND_COMMITTED identifies an explicit remote CallData completion.
   *
   * @generated from enum value: TERMINAL_KIND_COMMITTED = 1;
   */
  COMMITTED = 1,

  /**
   * TERMINAL_KIND_CANCELED identifies a remote CallCancel packet.
   *
   * @generated from enum value: TERMINAL_KIND_CANCELED = 2;
   */
  CANCELED = 2,

  /**
   * TERMINAL_KIND_TRANSPORT_LOST identifies a remote error or transport failure.
   *
   * @generated from enum value: TERMINAL_KIND_TRANSPORT_LOST = 3;
   */
  TRANSPORT_LOST = 3,

  /**
   * TERMINAL_KIND_CLOSED identifies a bare remote close without completion.
   *
   * @generated from enum value: TERMINAL_KIND_CLOSED = 4;
   */
  CLOSED = 4,

  /**
   * TERMINAL_KIND_ABANDONED identifies owner-context expiry without a remote terminal.
   *
   * @generated from enum value: TERMINAL_KIND_ABANDONED = 5;
   */
  ABANDONED = 5,
}

export const TerminalKind_Enum = /* @__PURE__ */ createEnumType(
  'srpc.TerminalKind',
  [
    [0, 'TERMINAL_KIND_UNSPECIFIED'],
    [1, 'TERMINAL_KIND_COMMITTED'],
    [2, 'TERMINAL_KIND_CANCELED'],
    [3, 'TERMINAL_KIND_TRANSPORT_LOST'],
    [4, 'TERMINAL_KIND_CLOSED'],
    [5, 'TERMINAL_KIND_ABANDONED'],
  ],
)

/**
 * CallStart requests starting a new RPC call.
 *
 * @generated from message srpc.CallStart
 */
export interface CallStart {
  /**
   * RpcService is the service to contact.
   * Must be set.
   *
   * @generated from field: string rpc_service = 1;
   */
  rpcService?: string
  /**
   * RpcMethod is the RPC method to call.
   * Must be set.
   *
   * @generated from field: string rpc_method = 2;
   */
  rpcMethod?: string
  /**
   * Data contains the request or the first message in the stream.
   * Optional if streaming.
   *
   * @generated from field: bytes data = 3;
   */
  data?: Uint8Array
  /**
   * DataIsZero indicates Data is set with an empty message.
   *
   * @generated from field: bool data_is_zero = 4;
   */
  dataIsZero?: boolean
}

export const CallStart: MessageType<CallStart> =
  /* @__PURE__ */ createMessageType({
    typeName: 'srpc.CallStart',
    fields: [
      { no: 1, name: 'rpc_service', kind: 'scalar', T: ScalarType.STRING },
      { no: 2, name: 'rpc_method', kind: 'scalar', T: ScalarType.STRING },
      { no: 3, name: 'data', kind: 'scalar', T: ScalarType.BYTES },
      { no: 4, name: 'data_is_zero', kind: 'scalar', T: ScalarType.BOOL },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * CallData contains a message in a streaming RPC sequence.
 *
 * @generated from message srpc.CallData
 */
export interface CallData {
  /**
   * Data contains the packet in the sequence.
   *
   * @generated from field: bytes data = 1;
   */
  data?: Uint8Array
  /**
   * DataIsZero indicates Data is set with an empty message.
   *
   * @generated from field: bool data_is_zero = 2;
   */
  dataIsZero?: boolean
  /**
   * Complete indicates the RPC call is completed.
   *
   * @generated from field: bool complete = 3;
   */
  complete?: boolean
  /**
   * Error contains any error that caused the RPC to fail.
   * If set, implies complete=true.
   *
   * @generated from field: string error = 4;
   */
  error?: string
}

export const CallData: MessageType<CallData> =
  /* @__PURE__ */ createMessageType({
    typeName: 'srpc.CallData',
    fields: [
      { no: 1, name: 'data', kind: 'scalar', T: ScalarType.BYTES },
      { no: 2, name: 'data_is_zero', kind: 'scalar', T: ScalarType.BOOL },
      { no: 3, name: 'complete', kind: 'scalar', T: ScalarType.BOOL },
      { no: 4, name: 'error', kind: 'scalar', T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * Packet is a message sent over a srpc packet connection.
 *
 * @generated from message srpc.Packet
 */
export interface Packet {
  /**
   * Body is the packet body.
   *
   * @generated from oneof srpc.Packet.body
   */
  body?:
    | {
        value?: undefined
        case: undefined
      }
    | {
        /**
         * CallStart initiates a new call.
         *
         * @generated from field: srpc.CallStart call_start = 1;
         */
        value: CallStart
        case: 'callStart'
      }
    | {
        /**
         * CallData is a message in a streaming RPC sequence.
         *
         * @generated from field: srpc.CallData call_data = 2;
         */
        value: CallData
        case: 'callData'
      }
    | {
        /**
         * CallCancel cancels the call.
         *
         * @generated from field: bool call_cancel = 3;
         */
        value: boolean
        case: 'callCancel'
      }
}

export const Packet: MessageType<Packet> = /* @__PURE__ */ createMessageType({
  typeName: 'srpc.Packet',
  fields: [
    {
      no: 1,
      name: 'call_start',
      kind: 'message',
      T: () => CallStart,
      oneof: 'body',
    },
    {
      no: 2,
      name: 'call_data',
      kind: 'message',
      T: () => CallData,
      oneof: 'body',
    },
    {
      no: 3,
      name: 'call_cancel',
      kind: 'scalar',
      T: ScalarType.BOOL,
      oneof: 'body',
    },
  ] satisfies readonly PartialFieldInfo[],
  packedByDefault: true,
})
