//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/starpc/srpc/rpcproto.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto_2epb_2eh
#define github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto;
}  // extern "C"
namespace srpc {
class CallData;
struct CallDataDefaultTypeInternal;
extern CallDataDefaultTypeInternal _CallData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CallData_class_data_;
class CallStart;
struct CallStartDefaultTypeInternal;
extern CallStartDefaultTypeInternal _CallStart_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CallStart_class_data_;
class Packet;
struct PacketDefaultTypeInternal;
extern PacketDefaultTypeInternal _Packet_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Packet_class_data_;
}  // namespace srpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace srpc {

// ===================================================================


// -------------------------------------------------------------------

class CallStart final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:srpc.CallStart) */ {
 public:
  inline CallStart() : CallStart(nullptr) {}
  ~CallStart() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CallStart* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CallStart));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CallStart(::google::protobuf::internal::ConstantInitialized);

  inline CallStart(const CallStart& from) : CallStart(nullptr, from) {}
  inline CallStart(CallStart&& from) noexcept
      : CallStart(nullptr, ::std::move(from)) {}
  inline CallStart& operator=(const CallStart& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallStart& operator=(CallStart&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallStart& default_instance() {
    return *reinterpret_cast<const CallStart*>(
        &_CallStart_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CallStart& a, CallStart& b) { a.Swap(&b); }
  inline void Swap(CallStart* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallStart* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallStart* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CallStart>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CallStart& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CallStart& from) { CallStart::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CallStart* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "srpc.CallStart"; }

  explicit CallStart(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CallStart(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CallStart& from);
  CallStart(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CallStart&& from) noexcept
      : CallStart(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRpcServiceFieldNumber = 1,
    kRpcMethodFieldNumber = 2,
    kDataFieldNumber = 3,
    kDataIsZeroFieldNumber = 4,
  };
  // string rpc_service = 1;
  void clear_rpc_service() ;
  const ::std::string& rpc_service() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rpc_service(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_rpc_service();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_rpc_service();
  void set_allocated_rpc_service(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_rpc_service() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_rpc_service(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_rpc_service();

  public:
  // string rpc_method = 2;
  void clear_rpc_method() ;
  const ::std::string& rpc_method() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rpc_method(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_rpc_method();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_rpc_method();
  void set_allocated_rpc_method(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_rpc_method() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_rpc_method(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_rpc_method();

  public:
  // bytes data = 3;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // bool data_is_zero = 4;
  void clear_data_is_zero() ;
  bool data_is_zero() const;
  void set_data_is_zero(bool value);

  private:
  bool _internal_data_is_zero() const;
  void _internal_set_data_is_zero(bool value);

  public:
  // @@protoc_insertion_point(class_scope:srpc.CallStart)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 44,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CallStart& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr rpc_service_;
    ::google::protobuf::internal::ArenaStringPtr rpc_method_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    bool data_is_zero_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CallStart_class_data_;
// -------------------------------------------------------------------

class CallData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:srpc.CallData) */ {
 public:
  inline CallData() : CallData(nullptr) {}
  ~CallData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CallData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CallData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CallData(::google::protobuf::internal::ConstantInitialized);

  inline CallData(const CallData& from) : CallData(nullptr, from) {}
  inline CallData(CallData&& from) noexcept
      : CallData(nullptr, ::std::move(from)) {}
  inline CallData& operator=(const CallData& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallData& operator=(CallData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallData& default_instance() {
    return *reinterpret_cast<const CallData*>(
        &_CallData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CallData& a, CallData& b) { a.Swap(&b); }
  inline void Swap(CallData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CallData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CallData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CallData& from) { CallData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CallData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "srpc.CallData"; }

  explicit CallData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CallData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CallData& from);
  CallData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CallData&& from) noexcept
      : CallData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 1,
    kErrorFieldNumber = 4,
    kDataIsZeroFieldNumber = 2,
    kCompleteFieldNumber = 3,
  };
  // bytes data = 1;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // string error = 4;
  void clear_error() ;
  const ::std::string& error() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_error(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_error();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_error();
  void set_allocated_error(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_error() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_error(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_error();

  public:
  // bool data_is_zero = 2;
  void clear_data_is_zero() ;
  bool data_is_zero() const;
  void set_data_is_zero(bool value);

  private:
  bool _internal_data_is_zero() const;
  void _internal_set_data_is_zero(bool value);

  public:
  // bool complete = 3;
  void clear_complete() ;
  bool complete() const;
  void set_complete(bool value);

  private:
  bool _internal_complete() const;
  void _internal_set_complete(bool value);

  public:
  // @@protoc_insertion_point(class_scope:srpc.CallData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 27,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CallData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::internal::ArenaStringPtr error_;
    bool data_is_zero_;
    bool complete_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CallData_class_data_;
// -------------------------------------------------------------------

class Packet final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:srpc.Packet) */ {
 public:
  inline Packet() : Packet(nullptr) {}
  ~Packet() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Packet* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Packet));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Packet(::google::protobuf::internal::ConstantInitialized);

  inline Packet(const Packet& from) : Packet(nullptr, from) {}
  inline Packet(Packet&& from) noexcept
      : Packet(nullptr, ::std::move(from)) {}
  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }
  inline Packet& operator=(Packet&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Packet& default_instance() {
    return *reinterpret_cast<const Packet*>(
        &_Packet_default_instance_);
  }
  enum BodyCase {
    kCallStart = 1,
    kCallData = 2,
    kCallCancel = 3,
    BODY_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Packet& a, Packet& b) { a.Swap(&b); }
  inline void Swap(Packet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Packet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Packet* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Packet>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Packet& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Packet& from) { Packet::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Packet* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "srpc.Packet"; }

  explicit Packet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Packet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Packet& from);
  Packet(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Packet&& from) noexcept
      : Packet(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCallStartFieldNumber = 1,
    kCallDataFieldNumber = 2,
    kCallCancelFieldNumber = 3,
  };
  // .srpc.CallStart call_start = 1;
  bool has_call_start() const;
  private:
  bool _internal_has_call_start() const;

  public:
  void clear_call_start() ;
  const ::srpc::CallStart& call_start() const;
  [[nodiscard]] ::srpc::CallStart* PROTOBUF_NULLABLE release_call_start();
  ::srpc::CallStart* PROTOBUF_NONNULL mutable_call_start();
  void set_allocated_call_start(::srpc::CallStart* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_call_start(::srpc::CallStart* PROTOBUF_NULLABLE value);
  ::srpc::CallStart* PROTOBUF_NULLABLE unsafe_arena_release_call_start();

  private:
  const ::srpc::CallStart& _internal_call_start() const;
  ::srpc::CallStart* PROTOBUF_NONNULL _internal_mutable_call_start();

  public:
  // .srpc.CallData call_data = 2;
  bool has_call_data() const;
  private:
  bool _internal_has_call_data() const;

  public:
  void clear_call_data() ;
  const ::srpc::CallData& call_data() const;
  [[nodiscard]] ::srpc::CallData* PROTOBUF_NULLABLE release_call_data();
  ::srpc::CallData* PROTOBUF_NONNULL mutable_call_data();
  void set_allocated_call_data(::srpc::CallData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_call_data(::srpc::CallData* PROTOBUF_NULLABLE value);
  ::srpc::CallData* PROTOBUF_NULLABLE unsafe_arena_release_call_data();

  private:
  const ::srpc::CallData& _internal_call_data() const;
  ::srpc::CallData* PROTOBUF_NONNULL _internal_mutable_call_data();

  public:
  // bool call_cancel = 3;
  bool has_call_cancel() const;
  void clear_call_cancel() ;
  bool call_cancel() const;
  void set_call_cancel(bool value);

  private:
  bool _internal_call_cancel() const;
  void _internal_set_call_cancel(bool value);

  public:
  void clear_body();
  BodyCase body_case() const;
  // @@protoc_insertion_point(class_scope:srpc.Packet)
 private:
  class _Internal;
  void set_has_call_start();
  void set_has_call_data();
  void set_has_call_cancel();
  inline bool has_body() const;
  inline void clear_has_body();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 3,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Packet& from_msg);
    union BodyUnion {
      constexpr BodyUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::srpc::CallStart* PROTOBUF_NULLABLE call_start_;
      ::srpc::CallData* PROTOBUF_NULLABLE call_data_;
      bool call_cancel_;
    } body_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Packet_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Packet

// .srpc.CallStart call_start = 1;
inline bool Packet::has_call_start() const {
  return body_case() == kCallStart;
}
inline bool Packet::_internal_has_call_start() const {
  return body_case() == kCallStart;
}
inline void Packet::set_has_call_start() {
  _impl_._oneof_case_[0] = kCallStart;
}
inline void Packet::clear_call_start() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kCallStart) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.call_start_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.call_start_);
    }
    clear_has_body();
  }
}
inline ::srpc::CallStart* PROTOBUF_NULLABLE Packet::release_call_start() {
  // @@protoc_insertion_point(field_release:srpc.Packet.call_start)
  if (body_case() == kCallStart) {
    clear_has_body();
    auto* temp = _impl_.body_.call_start_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.call_start_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::srpc::CallStart& Packet::_internal_call_start() const {
  return body_case() == kCallStart ? static_cast<const ::srpc::CallStart&>(*_impl_.body_.call_start_)
                     : reinterpret_cast<const ::srpc::CallStart&>(::srpc::_CallStart_default_instance_);
}
inline const ::srpc::CallStart& Packet::call_start() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:srpc.Packet.call_start)
  return _internal_call_start();
}
inline ::srpc::CallStart* PROTOBUF_NULLABLE Packet::unsafe_arena_release_call_start() {
  // @@protoc_insertion_point(field_unsafe_arena_release:srpc.Packet.call_start)
  if (body_case() == kCallStart) {
    clear_has_body();
    auto* temp = _impl_.body_.call_start_;
    _impl_.body_.call_start_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Packet::unsafe_arena_set_allocated_call_start(
    ::srpc::CallStart* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_body();
  if (value) {
    set_has_call_start();
    _impl_.body_.call_start_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:srpc.Packet.call_start)
}
inline ::srpc::CallStart* PROTOBUF_NONNULL Packet::_internal_mutable_call_start() {
  if (body_case() != kCallStart) {
    clear_body();
    set_has_call_start();
    _impl_.body_.call_start_ = 
        ::google::protobuf::Message::DefaultConstruct<::srpc::CallStart>(GetArena());
  }
  return _impl_.body_.call_start_;
}
inline ::srpc::CallStart* PROTOBUF_NONNULL Packet::mutable_call_start()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::srpc::CallStart* _msg = _internal_mutable_call_start();
  // @@protoc_insertion_point(field_mutable:srpc.Packet.call_start)
  return _msg;
}

// .srpc.CallData call_data = 2;
inline bool Packet::has_call_data() const {
  return body_case() == kCallData;
}
inline bool Packet::_internal_has_call_data() const {
  return body_case() == kCallData;
}
inline void Packet::set_has_call_data() {
  _impl_._oneof_case_[0] = kCallData;
}
inline void Packet::clear_call_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kCallData) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.call_data_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.call_data_);
    }
    clear_has_body();
  }
}
inline ::srpc::CallData* PROTOBUF_NULLABLE Packet::release_call_data() {
  // @@protoc_insertion_point(field_release:srpc.Packet.call_data)
  if (body_case() == kCallData) {
    clear_has_body();
    auto* temp = _impl_.body_.call_data_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.call_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::srpc::CallData& Packet::_internal_call_data() const {
  return body_case() == kCallData ? static_cast<const ::srpc::CallData&>(*_impl_.body_.call_data_)
                     : reinterpret_cast<const ::srpc::CallData&>(::srpc::_CallData_default_instance_);
}
inline const ::srpc::CallData& Packet::call_data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:srpc.Packet.call_data)
  return _internal_call_data();
}
inline ::srpc::CallData* PROTOBUF_NULLABLE Packet::unsafe_arena_release_call_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:srpc.Packet.call_data)
  if (body_case() == kCallData) {
    clear_has_body();
    auto* temp = _impl_.body_.call_data_;
    _impl_.body_.call_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Packet::unsafe_arena_set_allocated_call_data(
    ::srpc::CallData* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_body();
  if (value) {
    set_has_call_data();
    _impl_.body_.call_data_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:srpc.Packet.call_data)
}
inline ::srpc::CallData* PROTOBUF_NONNULL Packet::_internal_mutable_call_data() {
  if (body_case() != kCallData) {
    clear_body();
    set_has_call_data();
    _impl_.body_.call_data_ = 
        ::google::protobuf::Message::DefaultConstruct<::srpc::CallData>(GetArena());
  }
  return _impl_.body_.call_data_;
}
inline ::srpc::CallData* PROTOBUF_NONNULL Packet::mutable_call_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::srpc::CallData* _msg = _internal_mutable_call_data();
  // @@protoc_insertion_point(field_mutable:srpc.Packet.call_data)
  return _msg;
}

// bool call_cancel = 3;
inline bool Packet::has_call_cancel() const {
  return body_case() == kCallCancel;
}
inline void Packet::set_has_call_cancel() {
  _impl_._oneof_case_[0] = kCallCancel;
}
inline void Packet::clear_call_cancel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kCallCancel) {
    _impl_.body_.call_cancel_ = false;
    clear_has_body();
  }
}
inline bool Packet::call_cancel() const {
  // @@protoc_insertion_point(field_get:srpc.Packet.call_cancel)
  return _internal_call_cancel();
}
inline void Packet::set_call_cancel(bool value) {
  if (body_case() != kCallCancel) {
    clear_body();
    set_has_call_cancel();
  }
  _impl_.body_.call_cancel_ = value;
  // @@protoc_insertion_point(field_set:srpc.Packet.call_cancel)
}
inline bool Packet::_internal_call_cancel() const {
  if (body_case() == kCallCancel) {
    return _impl_.body_.call_cancel_;
  }
  return false;
}

inline bool Packet::has_body() const {
  return body_case() != BODY_NOT_SET;
}
inline void Packet::clear_has_body() {
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}
inline Packet::BodyCase Packet::body_case() const {
  return Packet::BodyCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// CallStart

// string rpc_service = 1;
inline void CallStart::clear_rpc_service() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_service_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CallStart::rpc_service() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:srpc.CallStart.rpc_service)
  return _internal_rpc_service();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CallStart::set_rpc_service(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.rpc_service_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:srpc.CallStart.rpc_service)
}
inline ::std::string* PROTOBUF_NONNULL CallStart::mutable_rpc_service()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_rpc_service();
  // @@protoc_insertion_point(field_mutable:srpc.CallStart.rpc_service)
  return _s;
}
inline const ::std::string& CallStart::_internal_rpc_service() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rpc_service_.Get();
}
inline void CallStart::_internal_set_rpc_service(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_service_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CallStart::_internal_mutable_rpc_service() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.rpc_service_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CallStart::release_rpc_service() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:srpc.CallStart.rpc_service)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.rpc_service_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.rpc_service_.Set("", GetArena());
  }
  return released;
}
inline void CallStart::set_allocated_rpc_service(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.rpc_service_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.rpc_service_.IsDefault()) {
    _impl_.rpc_service_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:srpc.CallStart.rpc_service)
}

// string rpc_method = 2;
inline void CallStart::clear_rpc_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_method_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& CallStart::rpc_method() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:srpc.CallStart.rpc_method)
  return _internal_rpc_method();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CallStart::set_rpc_method(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.rpc_method_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:srpc.CallStart.rpc_method)
}
inline ::std::string* PROTOBUF_NONNULL CallStart::mutable_rpc_method()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_rpc_method();
  // @@protoc_insertion_point(field_mutable:srpc.CallStart.rpc_method)
  return _s;
}
inline const ::std::string& CallStart::_internal_rpc_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rpc_method_.Get();
}
inline void CallStart::_internal_set_rpc_method(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_method_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CallStart::_internal_mutable_rpc_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.rpc_method_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CallStart::release_rpc_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:srpc.CallStart.rpc_method)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.rpc_method_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.rpc_method_.Set("", GetArena());
  }
  return released;
}
inline void CallStart::set_allocated_rpc_method(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.rpc_method_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.rpc_method_.IsDefault()) {
    _impl_.rpc_method_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:srpc.CallStart.rpc_method)
}

// bytes data = 3;
inline void CallStart::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& CallStart::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:srpc.CallStart.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CallStart::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:srpc.CallStart.data)
}
inline ::std::string* PROTOBUF_NONNULL CallStart::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:srpc.CallStart.data)
  return _s;
}
inline const ::std::string& CallStart::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void CallStart::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CallStart::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CallStart::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:srpc.CallStart.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void CallStart::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:srpc.CallStart.data)
}

// bool data_is_zero = 4;
inline void CallStart::clear_data_is_zero() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_is_zero_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool CallStart::data_is_zero() const {
  // @@protoc_insertion_point(field_get:srpc.CallStart.data_is_zero)
  return _internal_data_is_zero();
}
inline void CallStart::set_data_is_zero(bool value) {
  _internal_set_data_is_zero(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:srpc.CallStart.data_is_zero)
}
inline bool CallStart::_internal_data_is_zero() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_is_zero_;
}
inline void CallStart::_internal_set_data_is_zero(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_is_zero_ = value;
}

// -------------------------------------------------------------------

// CallData

// bytes data = 1;
inline void CallData::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CallData::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:srpc.CallData.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CallData::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:srpc.CallData.data)
}
inline ::std::string* PROTOBUF_NONNULL CallData::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:srpc.CallData.data)
  return _s;
}
inline const ::std::string& CallData::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void CallData::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CallData::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CallData::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:srpc.CallData.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void CallData::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:srpc.CallData.data)
}

// bool data_is_zero = 2;
inline void CallData::clear_data_is_zero() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_is_zero_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool CallData::data_is_zero() const {
  // @@protoc_insertion_point(field_get:srpc.CallData.data_is_zero)
  return _internal_data_is_zero();
}
inline void CallData::set_data_is_zero(bool value) {
  _internal_set_data_is_zero(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:srpc.CallData.data_is_zero)
}
inline bool CallData::_internal_data_is_zero() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_is_zero_;
}
inline void CallData::_internal_set_data_is_zero(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_is_zero_ = value;
}

// bool complete = 3;
inline void CallData::clear_complete() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.complete_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool CallData::complete() const {
  // @@protoc_insertion_point(field_get:srpc.CallData.complete)
  return _internal_complete();
}
inline void CallData::set_complete(bool value) {
  _internal_set_complete(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:srpc.CallData.complete)
}
inline bool CallData::_internal_complete() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.complete_;
}
inline void CallData::_internal_set_complete(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.complete_ = value;
}

// string error = 4;
inline void CallData::clear_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& CallData::error() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:srpc.CallData.error)
  return _internal_error();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CallData::set_error(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.error_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:srpc.CallData.error)
}
inline ::std::string* PROTOBUF_NONNULL CallData::mutable_error()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:srpc.CallData.error)
  return _s;
}
inline const ::std::string& CallData::_internal_error() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_.Get();
}
inline void CallData::_internal_set_error(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CallData::_internal_mutable_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.error_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CallData::release_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:srpc.CallData.error)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.error_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.error_.Set("", GetArena());
  }
  return released;
}
inline void CallData::set_allocated_error(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.error_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:srpc.CallData.error)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace srpc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto_2epb_2eh
