//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/starpc/srpc/rpcproto.proto
// Protobuf C++ Version: 6.33.4

#include "rpcproto.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace srpc {

inline constexpr CallStart::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        rpc_service_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rpc_method_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_is_zero_{false} {}

template <typename>
PROTOBUF_CONSTEXPR CallStart::CallStart(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CallStart_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CallStartDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CallStartDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CallStartDefaultTypeInternal() {}
  union {
    CallStart _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CallStartDefaultTypeInternal _CallStart_default_instance_;

inline constexpr CallData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_is_zero_{false},
        complete_{false} {}

template <typename>
PROTOBUF_CONSTEXPR CallData::CallData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CallData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CallDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CallDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CallDataDefaultTypeInternal() {}
  union {
    CallData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CallDataDefaultTypeInternal _CallData_default_instance_;

inline constexpr Packet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : body_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Packet::Packet(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Packet_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketDefaultTypeInternal() {}
  union {
    Packet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketDefaultTypeInternal _Packet_default_instance_;
}  // namespace srpc
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::srpc::Packet, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::srpc::Packet, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::srpc::Packet, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::srpc::Packet, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::srpc::Packet, _impl_.body_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::srpc::CallStart, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::srpc::CallStart, _impl_.rpc_service_),
        PROTOBUF_FIELD_OFFSET(::srpc::CallStart, _impl_.rpc_method_),
        PROTOBUF_FIELD_OFFSET(::srpc::CallStart, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::srpc::CallStart, _impl_.data_is_zero_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::srpc::CallData, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::srpc::CallData, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::srpc::CallData, _impl_.data_is_zero_),
        PROTOBUF_FIELD_OFFSET(::srpc::CallData, _impl_.complete_),
        PROTOBUF_FIELD_OFFSET(::srpc::CallData, _impl_.error_),
        0,
        2,
        3,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::srpc::Packet)},
        {6, sizeof(::srpc::CallStart)},
        {17, sizeof(::srpc::CallData)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::srpc::_Packet_default_instance_._instance,
    &::srpc::_CallStart_default_instance_._instance,
    &::srpc::_CallData_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n6github.com/aperturerobotics/starpc/srp"
    "c/rpcproto.proto\022\004srpc\"s\n\006Packet\022%\n\ncall"
    "_start\030\001 \001(\0132\017.srpc.CallStartH\000\022#\n\tcall_"
    "data\030\002 \001(\0132\016.srpc.CallDataH\000\022\025\n\013call_can"
    "cel\030\003 \001(\010H\000B\006\n\004body\"X\n\tCallStart\022\023\n\013rpc_"
    "service\030\001 \001(\t\022\022\n\nrpc_method\030\002 \001(\t\022\014\n\004dat"
    "a\030\003 \001(\014\022\024\n\014data_is_zero\030\004 \001(\010\"O\n\010CallDat"
    "a\022\014\n\004data\030\001 \001(\014\022\024\n\014data_is_zero\030\002 \001(\010\022\020\n"
    "\010complete\030\003 \001(\010\022\r\n\005error\030\004 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto = {
    false,
    false,
    358,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto,
    "github.com/aperturerobotics/starpc/srpc/rpcproto.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto,
};
namespace srpc {
// ===================================================================

class Packet::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::srpc::Packet, _impl_._oneof_case_);
};

void Packet::set_allocated_call_start(::srpc::CallStart* PROTOBUF_NULLABLE call_start) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (call_start) {
    ::google::protobuf::Arena* submessage_arena = call_start->GetArena();
    if (message_arena != submessage_arena) {
      call_start = ::google::protobuf::internal::GetOwnedMessage(message_arena, call_start, submessage_arena);
    }
    set_has_call_start();
    _impl_.body_.call_start_ = call_start;
  }
  // @@protoc_insertion_point(field_set_allocated:srpc.Packet.call_start)
}
void Packet::set_allocated_call_data(::srpc::CallData* PROTOBUF_NULLABLE call_data) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (call_data) {
    ::google::protobuf::Arena* submessage_arena = call_data->GetArena();
    if (message_arena != submessage_arena) {
      call_data = ::google::protobuf::internal::GetOwnedMessage(message_arena, call_data, submessage_arena);
    }
    set_has_call_data();
    _impl_.body_.call_data_ = call_data;
  }
  // @@protoc_insertion_point(field_set_allocated:srpc.Packet.call_data)
}
Packet::Packet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Packet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:srpc.Packet)
}
PROTOBUF_NDEBUG_INLINE Packet::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::srpc::Packet& from_msg)
      : body_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Packet::Packet(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Packet& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Packet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Packet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (body_case()) {
    case BODY_NOT_SET:
      break;
      case kCallStart:
        _impl_.body_.call_start_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.call_start_);
        break;
      case kCallData:
        _impl_.body_.call_data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.call_data_);
        break;
      case kCallCancel:
        _impl_.body_.call_cancel_ = from._impl_.body_.call_cancel_;
        break;
  }

  // @@protoc_insertion_point(copy_constructor:srpc.Packet)
}
PROTOBUF_NDEBUG_INLINE Packet::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : body_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Packet::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Packet::~Packet() {
  // @@protoc_insertion_point(destructor:srpc.Packet)
  SharedDtor(*this);
}
inline void Packet::SharedDtor(MessageLite& self) {
  Packet& this_ = static_cast<Packet&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_body()) {
    this_.clear_body();
  }
  this_._impl_.~Impl_();
}

void Packet::clear_body() {
// @@protoc_insertion_point(one_of_clear_start:srpc.Packet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (body_case()) {
    case kCallStart: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.call_start_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.call_start_);
      }
      break;
    }
    case kCallData: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.call_data_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.call_data_);
      }
      break;
    }
    case kCallCancel: {
      // No need to clear
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}


inline void* PROTOBUF_NONNULL Packet::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Packet(arena);
}
constexpr auto Packet::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Packet),
                                            alignof(Packet));
}
constexpr auto Packet::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Packet_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Packet::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Packet>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Packet::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Packet>(), &Packet::ByteSizeLong,
              &Packet::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Packet, _impl_._cached_size_),
          false,
      },
      &Packet::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Packet_class_data_ =
        Packet::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Packet::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Packet_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Packet_class_data_.tc_table);
  return Packet_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 2, 0, 2>
Packet::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Packet_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::srpc::Packet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .srpc.CallStart call_start = 1;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.body_.call_start_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .srpc.CallData call_data = 2;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.body_.call_data_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool call_cancel = 3;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.body_.call_cancel_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kBool)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::srpc::CallStart>()},
      {::_pbi::TcParser::GetTable<::srpc::CallData>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Packet::Clear() {
// @@protoc_insertion_point(message_clear_start:srpc.Packet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_body();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Packet::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Packet& this_ = static_cast<const Packet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Packet::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Packet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:srpc.Packet)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.body_case()) {
    case kCallStart: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.body_.call_start_, this_._impl_.body_.call_start_->GetCachedSize(), target,
          stream);
      break;
    }
    case kCallData: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.body_.call_data_, this_._impl_.body_.call_data_->GetCachedSize(), target,
          stream);
      break;
    }
    case kCallCancel: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_call_cancel(), target);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:srpc.Packet)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Packet::ByteSizeLong(const MessageLite& base) {
  const Packet& this_ = static_cast<const Packet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Packet::ByteSizeLong() const {
  const Packet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:srpc.Packet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.body_case()) {
    // .srpc.CallStart call_start = 1;
    case kCallStart: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.call_start_);
      break;
    }
    // .srpc.CallData call_data = 2;
    case kCallData: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.call_data_);
      break;
    }
    // bool call_cancel = 3;
    case kCallCancel: {
      total_size += 2;
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Packet::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Packet*>(&to_msg);
  auto& from = static_cast<const Packet&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:srpc.Packet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_body();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kCallStart: {
        if (oneof_needs_init) {
          _this->_impl_.body_.call_start_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.call_start_);
        } else {
          _this->_impl_.body_.call_start_->MergeFrom(*from._impl_.body_.call_start_);
        }
        break;
      }
      case kCallData: {
        if (oneof_needs_init) {
          _this->_impl_.body_.call_data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.call_data_);
        } else {
          _this->_impl_.body_.call_data_->MergeFrom(*from._impl_.body_.call_data_);
        }
        break;
      }
      case kCallCancel: {
        _this->_impl_.body_.call_cancel_ = from._impl_.body_.call_cancel_;
        break;
      }
      case BODY_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Packet::CopyFrom(const Packet& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:srpc.Packet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Packet::InternalSwap(Packet* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.body_, other->_impl_.body_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Packet::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CallStart::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CallStart>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CallStart, _impl_._has_bits_);
};

CallStart::CallStart(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CallStart_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:srpc.CallStart)
}
PROTOBUF_NDEBUG_INLINE CallStart::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::srpc::CallStart& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        rpc_service_(arena, from.rpc_service_),
        rpc_method_(arena, from.rpc_method_),
        data_(arena, from.data_) {}

CallStart::CallStart(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CallStart& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CallStart_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CallStart* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.data_is_zero_ = from._impl_.data_is_zero_;

  // @@protoc_insertion_point(copy_constructor:srpc.CallStart)
}
PROTOBUF_NDEBUG_INLINE CallStart::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        rpc_service_(arena),
        rpc_method_(arena),
        data_(arena) {}

inline void CallStart::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.data_is_zero_ = {};
}
CallStart::~CallStart() {
  // @@protoc_insertion_point(destructor:srpc.CallStart)
  SharedDtor(*this);
}
inline void CallStart::SharedDtor(MessageLite& self) {
  CallStart& this_ = static_cast<CallStart&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.rpc_service_.Destroy();
  this_._impl_.rpc_method_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CallStart::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CallStart(arena);
}
constexpr auto CallStart::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CallStart),
                                            alignof(CallStart));
}
constexpr auto CallStart::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CallStart_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CallStart::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CallStart>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CallStart::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CallStart>(), &CallStart::ByteSizeLong,
              &CallStart::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CallStart, _impl_._cached_size_),
          false,
      },
      &CallStart::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CallStart_class_data_ =
        CallStart::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CallStart::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CallStart_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CallStart_class_data_.tc_table);
  return CallStart_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 44, 2>
CallStart::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CallStart, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CallStart_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::srpc::CallStart>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool data_is_zero = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CallStart, _impl_.data_is_zero_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(CallStart, _impl_.data_is_zero_)}},
    // string rpc_service = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CallStart, _impl_.rpc_service_)}},
    // string rpc_method = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(CallStart, _impl_.rpc_method_)}},
    // bytes data = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(CallStart, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string rpc_service = 1;
    {PROTOBUF_FIELD_OFFSET(CallStart, _impl_.rpc_service_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string rpc_method = 2;
    {PROTOBUF_FIELD_OFFSET(CallStart, _impl_.rpc_method_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes data = 3;
    {PROTOBUF_FIELD_OFFSET(CallStart, _impl_.data_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bool data_is_zero = 4;
    {PROTOBUF_FIELD_OFFSET(CallStart, _impl_.data_is_zero_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\16\13\12\0\0\0\0\0"
    "srpc.CallStart"
    "rpc_service"
    "rpc_method"
  }},
};
PROTOBUF_NOINLINE void CallStart::Clear() {
// @@protoc_insertion_point(message_clear_start:srpc.CallStart)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.rpc_service_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.rpc_method_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.data_is_zero_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CallStart::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CallStart& this_ = static_cast<const CallStart&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CallStart::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CallStart& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:srpc.CallStart)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string rpc_service = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_rpc_service().empty()) {
      const ::std::string& _s = this_._internal_rpc_service();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "srpc.CallStart.rpc_service");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string rpc_method = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_rpc_method().empty()) {
      const ::std::string& _s = this_._internal_rpc_method();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "srpc.CallStart.rpc_method");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // bytes data = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // bool data_is_zero = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_data_is_zero() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_data_is_zero(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:srpc.CallStart)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CallStart::ByteSizeLong(const MessageLite& base) {
  const CallStart& this_ = static_cast<const CallStart&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CallStart::ByteSizeLong() const {
  const CallStart& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:srpc.CallStart)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string rpc_service = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_rpc_service().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_rpc_service());
      }
    }
    // string rpc_method = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_rpc_method().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_rpc_method());
      }
    }
    // bytes data = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_data());
      }
    }
    // bool data_is_zero = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_data_is_zero() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CallStart::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CallStart*>(&to_msg);
  auto& from = static_cast<const CallStart&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:srpc.CallStart)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_rpc_service().empty()) {
        _this->_internal_set_rpc_service(from._internal_rpc_service());
      } else {
        if (_this->_impl_.rpc_service_.IsDefault()) {
          _this->_internal_set_rpc_service("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_rpc_method().empty()) {
        _this->_internal_set_rpc_method(from._internal_rpc_method());
      } else {
        if (_this->_impl_.rpc_method_.IsDefault()) {
          _this->_internal_set_rpc_method("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_data_is_zero() != 0) {
        _this->_impl_.data_is_zero_ = from._impl_.data_is_zero_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CallStart::CopyFrom(const CallStart& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:srpc.CallStart)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CallStart::InternalSwap(CallStart* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rpc_service_, &other->_impl_.rpc_service_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rpc_method_, &other->_impl_.rpc_method_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  swap(_impl_.data_is_zero_, other->_impl_.data_is_zero_);
}

::google::protobuf::Metadata CallStart::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CallData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CallData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CallData, _impl_._has_bits_);
};

CallData::CallData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CallData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:srpc.CallData)
}
PROTOBUF_NDEBUG_INLINE CallData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::srpc::CallData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        data_(arena, from.data_),
        error_(arena, from.error_) {}

CallData::CallData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CallData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CallData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CallData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, data_is_zero_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, data_is_zero_),
           offsetof(Impl_, complete_) -
               offsetof(Impl_, data_is_zero_) +
               sizeof(Impl_::complete_));

  // @@protoc_insertion_point(copy_constructor:srpc.CallData)
}
PROTOBUF_NDEBUG_INLINE CallData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        data_(arena),
        error_(arena) {}

inline void CallData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, data_is_zero_),
           0,
           offsetof(Impl_, complete_) -
               offsetof(Impl_, data_is_zero_) +
               sizeof(Impl_::complete_));
}
CallData::~CallData() {
  // @@protoc_insertion_point(destructor:srpc.CallData)
  SharedDtor(*this);
}
inline void CallData::SharedDtor(MessageLite& self) {
  CallData& this_ = static_cast<CallData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.data_.Destroy();
  this_._impl_.error_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CallData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CallData(arena);
}
constexpr auto CallData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CallData),
                                            alignof(CallData));
}
constexpr auto CallData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CallData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CallData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CallData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CallData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CallData>(), &CallData::ByteSizeLong,
              &CallData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CallData, _impl_._cached_size_),
          false,
      },
      &CallData::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CallData_class_data_ =
        CallData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CallData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CallData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CallData_class_data_.tc_table);
  return CallData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 27, 2>
CallData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CallData, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CallData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::srpc::CallData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(CallData, _impl_.error_)}},
    // bytes data = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CallData, _impl_.data_)}},
    // bool data_is_zero = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CallData, _impl_.data_is_zero_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(CallData, _impl_.data_is_zero_)}},
    // bool complete = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CallData, _impl_.complete_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(CallData, _impl_.complete_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes data = 1;
    {PROTOBUF_FIELD_OFFSET(CallData, _impl_.data_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bool data_is_zero = 2;
    {PROTOBUF_FIELD_OFFSET(CallData, _impl_.data_is_zero_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool complete = 3;
    {PROTOBUF_FIELD_OFFSET(CallData, _impl_.complete_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string error = 4;
    {PROTOBUF_FIELD_OFFSET(CallData, _impl_.error_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\0\0\5\0\0\0"
    "srpc.CallData"
    "error"
  }},
};
PROTOBUF_NOINLINE void CallData::Clear() {
// @@protoc_insertion_point(message_clear_start:srpc.CallData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.error_.ClearNonDefaultToEmpty();
    }
  }
  ::memset(&_impl_.data_is_zero_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.complete_) -
      reinterpret_cast<char*>(&_impl_.data_is_zero_)) + sizeof(_impl_.complete_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CallData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CallData& this_ = static_cast<const CallData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CallData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CallData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:srpc.CallData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes data = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bool data_is_zero = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_data_is_zero() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_data_is_zero(), target);
    }
  }

  // bool complete = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_complete() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_complete(), target);
    }
  }

  // string error = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_error().empty()) {
      const ::std::string& _s = this_._internal_error();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "srpc.CallData.error");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:srpc.CallData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CallData::ByteSizeLong(const MessageLite& base) {
  const CallData& this_ = static_cast<const CallData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CallData::ByteSizeLong() const {
  const CallData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:srpc.CallData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // bytes data = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_data());
      }
    }
    // string error = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_error().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_error());
      }
    }
    // bool data_is_zero = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_data_is_zero() != 0) {
        total_size += 2;
      }
    }
    // bool complete = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_complete() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CallData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CallData*>(&to_msg);
  auto& from = static_cast<const CallData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:srpc.CallData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_error().empty()) {
        _this->_internal_set_error(from._internal_error());
      } else {
        if (_this->_impl_.error_.IsDefault()) {
          _this->_internal_set_error("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_data_is_zero() != 0) {
        _this->_impl_.data_is_zero_ = from._impl_.data_is_zero_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_complete() != 0) {
        _this->_impl_.complete_ = from._impl_.complete_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CallData::CopyFrom(const CallData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:srpc.CallData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CallData::InternalSwap(CallData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_, &other->_impl_.error_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CallData, _impl_.complete_)
      + sizeof(CallData::_impl_.complete_)
      - PROTOBUF_FIELD_OFFSET(CallData, _impl_.data_is_zero_)>(
          reinterpret_cast<char*>(&_impl_.data_is_zero_),
          reinterpret_cast<char*>(&other->_impl_.data_is_zero_));
}

::google::protobuf::Metadata CallData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace srpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fsrpc_2frpcproto_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
