//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/starpc/echo/echo.proto
// Protobuf C++ Version: 6.33.4

#include "echo.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace echo {

inline constexpr EchoMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        body_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR EchoMsg::EchoMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EchoMsg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EchoMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EchoMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EchoMsgDefaultTypeInternal() {}
  union {
    EchoMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EchoMsgDefaultTypeInternal _EchoMsg_default_instance_;
}  // namespace echo
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::echo::EchoMsg, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::echo::EchoMsg, _impl_.body_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::echo::EchoMsg)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::echo::_EchoMsg_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n2github.com/aperturerobotics/starpc/ech"
    "o/echo.proto\022\004echo\032<github.com/aperturer"
    "obotics/starpc/rpcstream/rpcstream.proto"
    "\032\033google/protobuf/empty.proto\"\027\n\007EchoMsg"
    "\022\014\n\004body\030\001 \001(\t2\320\002\n\006Echoer\022$\n\004Echo\022\r.echo"
    ".EchoMsg\032\r.echo.EchoMsg\0222\n\020EchoServerStr"
    "eam\022\r.echo.EchoMsg\032\r.echo.EchoMsg0\001\0222\n\020E"
    "choClientStream\022\r.echo.EchoMsg\032\r.echo.Ec"
    "hoMsg(\001\0222\n\016EchoBidiStream\022\r.echo.EchoMsg"
    "\032\r.echo.EchoMsg(\0010\001\022G\n\tRpcStream\022\032.rpcst"
    "ream.RpcStreamPacket\032\032.rpcstream.RpcStre"
    "amPacket(\0010\001\022;\n\tDoNothing\022\026.google.proto"
    "buf.Empty\032\026.google.protobuf.Emptyb\006proto"
    "3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto_deps[2] = {
        &::descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2frpcstream_2frpcstream_2eproto,
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto = {
    false,
    false,
    521,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto,
    "github.com/aperturerobotics/starpc/echo/echo.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto_once,
    descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto,
};
namespace echo {
// ===================================================================

class EchoMsg::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EchoMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EchoMsg, _impl_._has_bits_);
};

EchoMsg::EchoMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EchoMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:echo.EchoMsg)
}
PROTOBUF_NDEBUG_INLINE EchoMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::echo::EchoMsg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        body_(arena, from.body_) {}

EchoMsg::EchoMsg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EchoMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EchoMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EchoMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:echo.EchoMsg)
}
PROTOBUF_NDEBUG_INLINE EchoMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        body_(arena) {}

inline void EchoMsg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EchoMsg::~EchoMsg() {
  // @@protoc_insertion_point(destructor:echo.EchoMsg)
  SharedDtor(*this);
}
inline void EchoMsg::SharedDtor(MessageLite& self) {
  EchoMsg& this_ = static_cast<EchoMsg&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.body_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EchoMsg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EchoMsg(arena);
}
constexpr auto EchoMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EchoMsg),
                                            alignof(EchoMsg));
}
constexpr auto EchoMsg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EchoMsg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EchoMsg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EchoMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EchoMsg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EchoMsg>(), &EchoMsg::ByteSizeLong,
              &EchoMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EchoMsg, _impl_._cached_size_),
          false,
      },
      &EchoMsg::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EchoMsg_class_data_ =
        EchoMsg::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EchoMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EchoMsg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EchoMsg_class_data_.tc_table);
  return EchoMsg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 25, 2>
EchoMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EchoMsg, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EchoMsg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::echo::EchoMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string body = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(EchoMsg, _impl_.body_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string body = 1;
    {PROTOBUF_FIELD_OFFSET(EchoMsg, _impl_.body_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\4\0\0\0\0\0\0"
    "echo.EchoMsg"
    "body"
  }},
};
PROTOBUF_NOINLINE void EchoMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:echo.EchoMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.body_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EchoMsg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EchoMsg& this_ = static_cast<const EchoMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EchoMsg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EchoMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:echo.EchoMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string body = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_body().empty()) {
      const ::std::string& _s = this_._internal_body();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "echo.EchoMsg.body");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:echo.EchoMsg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EchoMsg::ByteSizeLong(const MessageLite& base) {
  const EchoMsg& this_ = static_cast<const EchoMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EchoMsg::ByteSizeLong() const {
  const EchoMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:echo.EchoMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string body = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_body().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_body());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EchoMsg::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<EchoMsg*>(&to_msg);
  auto& from = static_cast<const EchoMsg&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:echo.EchoMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_body().empty()) {
      _this->_internal_set_body(from._internal_body());
    } else {
      if (_this->_impl_.body_.IsDefault()) {
        _this->_internal_set_body("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void EchoMsg::CopyFrom(const EchoMsg& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:echo.EchoMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EchoMsg::InternalSwap(EchoMsg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.body_, &other->_impl_.body_, arena);
}

::google::protobuf::Metadata EchoMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace echo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fstarpc_2fecho_2fecho_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
