// Code generated by protoc-gen-srpc. DO NOT EDIT.
// protoc-gen-srpc version: v0.0.0-20220611014014-aa9dc5523865
// source: github.com/aperturerobotics/starpc/echo/echo.proto

package echo

import (
	context "context"

	srpc "github.com/aperturerobotics/starpc/srpc"
)

type SRPCEchoerClient interface {
	SRPCClient() srpc.Client

	Echo(ctx context.Context, in *EchoMsg) (*EchoMsg, error)
}

type srpcEchoerClient struct {
	cc srpc.Client
}

func NewSRPCEchoerClient(cc srpc.Client) SRPCEchoerClient {
	return &srpcEchoerClient{cc}
}

func (c *srpcEchoerClient) SRPCClient() srpc.Client { return c.cc }

func (c *srpcEchoerClient) Echo(ctx context.Context, in *EchoMsg) (*EchoMsg, error) {
	out := new(EchoMsg)
	err := c.cc.Invoke(ctx, "echo.Echoer", "Echo", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type SRPCEchoerServer interface {
	Echo(context.Context, *EchoMsg) (*EchoMsg, error)
}

type SRPCEchoerUnimplementedServer struct{}

func (s *SRPCEchoerUnimplementedServer) Echo(context.Context, *EchoMsg) (*EchoMsg, error) {
	return nil, srpc.ErrUnimplemented
}

const SRPCEchoerServiceID = "echo.Echoer"

type SRPCEchoerHandler struct {
	impl SRPCEchoerServer
}

func (SRPCEchoerHandler) GetServiceID() string { return SRPCEchoerServiceID }

func (SRPCEchoerHandler) GetMethodIDs() []string {
	return []string{
		"Echo",
	}
}

func (d *SRPCEchoerHandler) InvokeMethod(
	serviceID, methodID string,
	strm srpc.Stream,
) (bool, error) {
	if serviceID != "" && serviceID != d.GetServiceID() {
		return false, nil
	}

	switch methodID {
	case "Echo":
		return true, d.InvokeMethod_Echo(d.impl, strm)
	default:
		return false, nil
	}
}

func (SRPCEchoerHandler) InvokeMethod_Echo(impl SRPCEchoerServer, strm srpc.Stream) error {
	req := new(EchoMsg)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.Echo(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func SRPCRegisterEchoer(mux srpc.Mux, impl SRPCEchoerServer) error {
	return mux.Register(&SRPCEchoerHandler{})
}

type SRPCEchoer_EchoStream interface {
	srpc.Stream
	SendAndClose(*EchoMsg) error
}

type srpcEchoer_EchoStream struct {
	srpc.Stream
}

func (x *srpcEchoer_EchoStream) SendAndClose(m *EchoMsg) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}
